import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

import { Product, FooterBanner, HeroBanner } from '../components';
import { client } from '../lib/client';
interface HomeInterface {
    products: [];
    bannerData: any;
}

export interface Product {
    _createdAt: Date;
    _id: string;
    _rev: string;
    _type: string;
    _updatedAt: Date;
    details: string;
    image: [
        {
            _key: string;
            _type: string;
            asset: {
                _ref: string;
                _type: string;
            };
        }
    ];
    name: string;
    price: number;
    slug: {
        _type: string;
        current: string;
    };
}

const Home: NextPage<HomeInterface> = ({ products, bannerData }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <HeroBanner heroBanner={bannerData.length && bannerData[0]} />
            <div className="grid justify-items-center ">
                <h2 className="text-2xl font-bold text-amber-700">
                    Best selling products
                </h2>
                <p className="text-neutral-500">Speakers of many variations</p>
            </div>
            <div className="flex justify-center">
                {products?.map((product: Product) => (
                    <Product key={product._id} product={product} />
                ))}
            </div>
            {console.log(bannerData[0])}
            <FooterBanner footerBanner={bannerData && bannerData[0]} />
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async () => {
    const query = '*[_type == "product"]';
    const products = await client.fetch(query);
    const bannerQuery = '*[_type == "banner"]';
    const bannerData = await client.fetch(bannerQuery);

    return {
        props: {
            products,
            bannerData,
        },
    };
};

export default Home;
